# Generated by Django 3.2 on 2023-10-19 14:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='stream',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock())], default='', use_json_field=None),
            preserve_default=False,
        ),
    ]
