# Generated by Django 3.2 on 2023-10-19 14:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='stream',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock())], use_json_field=True),
        ),
    ]
